CREATE TABLE USUARIO (
  ID INTEGER PRIMARY KEY,
  NAME TEXT,
  USERNAME TEXT,
  IS_BOT INTEGER,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME,
  R_USUARIO TEXT
)

CREATE TABLE LOG_CONSULTA  (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CONSULTA TEXT,
  ID_USUARIO INTEGER,
  USUARIO TEXT,
  NOMBRE TEXT,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME,
  R_USUARIO TEXT
)

CREATE TABLE MINUTA_CASINO (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  PERIODO TEXT,
  URL TEXT,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME,
  R_USUARIO TEXT
)

CREATE TABLE LOTO (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  FECHA DATETIME,
  MONTO INTEGER,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME,
  R_USUARIO TEXT
)

CREATE TABLE IP_ZOOM (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  IP TEXT,
  VIGENTE INTEGER,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME,
  R_USUARIO TEXT
)

CREATE TABLE T_ACCESO(
	ID INTEGER PRIMARY KEY,
	DESCRIPCION TEXT,
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT DATETIME,
	R_USUARIO TEXT
)

CREATE TABLE PERMISO(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  COMANDO TEXT,
  T_ACCESO INTEGER,
  VIGENTE INTEGER,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME,
  R_USUARIO TEXT,
  CONSTRAINT PERMISO_T_ACCESO_FK FOREIGN KEY (T_ACCESO) REFERENCES T_ACCESO(ID)
)

CREATE TABLE PERMISO_USUARIO(
  ID_PERMISO INTEGER,
  ID_USUARIO INTEGER,
  VIGENTE INTEGER,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME,
  R_USUARIO TEXT,
  PRIMARY KEY (ID_PERMISO, ID_USUARIO)
)