CREATE TABLE USUARIO (
  ID INTEGER PRIMARY KEY,
  NAME TEXT,
  USERNAME TEXT,
  IS_BOT INTEGER,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME,
  R_USUARIO TEXT
)

CREATE TABLE LOG_CONSULTA  (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CONSULTA TEXT,
  ID_USUARIO INTEGER,
  USUARIO TEXT,
  NOMBRE TEXT,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME,
  R_USUARIO TEXT
)

CREATE TABLE MINUTA_CASINO (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  PERIODO TEXT,
  URL TEXT,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME,
  R_USUARIO TEXT
)

CREATE TABLE LOTO (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  FECHA DATETIME,
  MONTO INTEGER,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME,
  R_USUARIO TEXT
)

CREATE TABLE IP_ZOOM (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  IP TEXT,
  VIGENTE INTEGER,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME,
  R_USUARIO TEXT
)

CREATE TABLE T_ACCESO(
	ID INTEGER PRIMARY KEY,
	DESCRIPCION TEXT,
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT DATETIME,
	R_USUARIO TEXT
)

CREATE TABLE PERMISO(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  COMANDO TEXT,
  T_ACCESO INTEGER,
  VIGENTE INTEGER,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME,
  R_USUARIO TEXT,
  CONSTRAINT PERMISO_T_ACCESO_FK FOREIGN KEY (T_ACCESO) REFERENCES T_ACCESO(ID)
)

CREATE TABLE PERMISO_USUARIO(
  ID_PERMISO INTEGER,
  ID_USUARIO INTEGER,
  VIGENTE INTEGER,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME,
  R_USUARIO TEXT,
  PRIMARY KEY (ID_PERMISO, ID_USUARIO)
)

CREATE TABLE AGENDA_CRON (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  EXPRESION_CRON TEXT,
  FUNCION TEXT,
  VIGENTE INTEGER,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME,
  R_USUARIO TEXT
)

CREATE TABLE DESTINATARIO_CRON (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_USUARIO INTEGER,
  FUNCION_CRON TEXT,
  VIGENTE INTEGER,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME,
  R_USUARIO TEXT
)

CREATE TABLE MEDICAMENTO (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NOMBRE TEXT,
  DOSIS_DIARIA INTEGER,
  VIGENTE INTEGER,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME,
  R_USUARIO TEXT
)

CREATE TABLE COMPRA (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  FECHA DATETIME,
  VIGENTE INTEGER,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME,
  R_USUARIO TEXT
)

CREATE TABLE COMPRA_MEDICAMENTO (
  ID_MEDICAMENTO INTEGER,
  ID_COMPRA INTEGER,
  CANTIDAD INTEGER,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME,
  R_USUARIO TEXT,
  PRIMARY KEY (ID_MEDICAMENTO, ID_COMPRA),
  CONSTRAINT COMPRA_MEDICAMENTO_MEDICAMENTO_FK FOREIGN KEY (ID_MEDICAMENTO) REFERENCES MEDICAMENTO(ID),
  CONSTRAINT COMPRA_MEDICAMENTO_COMPRA_FK FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA(ID)
)

CREATE TABLE REGIMEN_MEDICO (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CANTIDAD INTEGER,
  DESC_DOSIS TEXT,
  NOTA TEXT,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME,
  R_USUARIO TEXT
)

CREATE TABLE MEDICAMENTO_REGIMEN_MEDICO (
  FECHA DATETIME,
  ID_MEDICAMENTO INTEGER,
  ID_REGIMEN_MEDICO INTEGER,
  CANTIDAD INTEGER,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME,
  R_USUARIO TEXT,
  PRIMARY KEY (FECHA, ID_MEDICAMENTO, ID_REGIMEN_MEDICO),
  CONSTRAINT MEDI_REGI_MEDI_REGI_MEDI_FK FOREIGN KEY (ID_REGIMEN_MEDICO) REFERENCES REGIMEN_MEDICO(ID),
  CONSTRAINT MEDI_REGI_MEDI_MEDI_FK FOREIGN KEY (ID_MEDICAMENTO) REFERENCES MEDICAMENTO(ID)
)