CREATE TABLE USUARIO (
  ID INTEGER PRIMARY KEY,
  NAME TEXT,
  USERNAME TEXT,
  IS_BOT INTEGER,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME,
  R_USUARIO TEXT
)

CREATE TABLE LOG_CONSULTA  (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CONSULTA TEXT,
  ID_USUARIO INTEGER,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME,
  R_USUARIO TEXT
)