CREATE VIEW V_MEDIC_COMPRADOS_VIG
AS 
SELECT 
	M.ID
	, M.NOMBRE
	, M.DOSIS_DIARIA 
	, SUM(CM.CANTIDAD) AS 'COMPRADO' 
FROM MEDICAMENTO M
INNER JOIN COMPRA_MEDICAMENTO CM
ON CM.ID_MEDICAMENTO = M.ID 
WHERE M.VIGENTE = 1
GROUP BY M.ID 

CREATE VIEW V_MEDIC_CONSUMIDO_VIG
AS 
SELECT 
	M.ID
	, M.NOMBRE 
	, SUM(MRM.CANTIDAD) AS 'CONSUMIDO'
FROM MEDICAMENTO M 
INNER JOIN MEDICAMENTO_REGIMEN_MEDICO MRM 
ON MRM.ID_MEDICAMENTO = M.ID 
AND MRM.FECHA <= date('now', 'localtime') 
WHERE M.VIGENTE = 1
GROUP BY M.ID 

CREATE VIEW V_MEDIC_CONSUM_ACUM
AS 
SELECT 
	ID_MEDICAMENTO
	, FECHA 
	, SUM(CANTIDAD) 
		OVER (
			PARTITION BY ID_MEDICAMENTO ORDER BY FECHA
		) AS ACUMULADO
FROM MEDICAMENTO_REGIMEN_MEDICO MRM